apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment-no-scc
  namespace: scc-non-generating-no-field-no-annotation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: unconfined
    spec:
      serviceAccount: busybox-serviceaccount-no-scc
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c", "while true; do echo $(date); sleep 10; done"]
