kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: my-scc-runtime-default
seccompProfiles:
- "*"
allowPrivilegedContainer: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- busybox-serviceaccount-no-scc
