apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scc-runtime-default
subjects:
- kind: ServiceAccount
  name: busybox-service-account
  namespace: scc-plays-runtime-default
