kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: my-scc-wildcard
seccompProfiles:
- "*"
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- ibihim
