apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: unconfined-pod-no-annotations-fields
  labels:
    app: busybox
spec:
  securityContext:
    seccompProfile:
      type: Unconfined
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo $(date); sleep 10; done"]
