apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: unconfined-container-annotations-fields-conflict
  labels:
    app: busybox
  annotations:
    container.seccomp.security.alpha.kubernetes.io/busybox: unconfined
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo $(date); sleep 10; done"]
    securityContext:
      type: RuntimeDefault
