apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: wildcard-pod-no-annotations-fields
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      securityContext:
        seccompProfile:
          type: Unconfined
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c", "while true; do echo $(date); sleep 10; done"]
