apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: wildcard-container-no-annotations-fields
  labels:
    app: busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo $(date); sleep 10; done"]
    securityContext:
      type: Unconfined
