apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: wildcard-pod-annotations-no-fields
  labels:
    app: busybox
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: unconfined
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo $(date); sleep 10; done"]
