apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: {{.Namespace}}
  labels:
    app: busybox
  {{- range .Annotations}}
  annotations:
    {{.}}
  {{- end}}
spec:
  {{- if .PodField}}
  securityContext:
    seccompProfile:
      type: {{.PodField}}
  {{- end}}
  containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo $(date); sleep 10; done"]
    {{- if .ContainerField}}
    securityContext:
      type: {{.ContainerField}}
    {{- end}}
