apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-cluster-role
subjects:
- kind: ServiceAccount
  name: nginx-service-account
  namespace: scc-plays
