apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: seccomp-cluster-role
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - my-scc-seccomp
