kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: my-scc-seccomp
seccompProfiles:
- unconfined
- runtime/default
allowPrivilegedContainer: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny

