apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: p0t-sekurity-cluster-role
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: p0t-sekurity-role-binding
  namespace: p0t-sekurity
subjects:
- kind: ServiceAccount
  name: p0t-sekurity-sa
  namespace: p0t-sekurity
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: p0t-sekurity-cluster-role

