apiVersion: apps/v1
kind: Deployment
metadata:
  name: with-conflicts
  namespace: scc-plays-unconfined-conflicting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: unconfined
    spec:
      serviceAccount: busybox-service-account
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c", "while true; do echo $(date); sleep 10; done"]
